version: '3.8'

services:
  ollama-container:
    image: achivementsai/ollama-image:latest
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  streamlit-app:
    image: achivementsai/streamlit-image:latest
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_BASE_URL=http://ollama-image:11434
    depends_on:
      ollama-container:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  ollama_data: